import { useEffect, useRef, useState } from 'react';
import { ChevronDown, LayoutGrid, Loader2, Mic, Play, Square } from 'lucide-react';
import { fetchSampleText, previewUrl } from '../lib/api';
import type { Voice } from '../types';

interface Props {
  voices: Voice[];
  value: string;
  speed: number;
  disabled: boolean;
  onChange: (voiceId: string) => void;
  onBrowse: () => void;
}


/**
 * Voice picker with an audible preview.
 *
 * The sample is generated by the same Piper call the real narration uses, at
 * the currently selected speed, so what you hear is what the book will sound
 * like. The server caches each sample, making repeat comparisons instant.
 */
export function VoiceSelector({ voices, value, speed, disabled, onChange, onBrowse }: Props) {
  const [sampleText, setSampleText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [previewError, setPreviewError] = useState<string | null>(null);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const hasVoices = voices.length > 0;
  const selected = voices.find((voice) => voice.id === value);

  // Group by the heading the backend assigns (accent for Piper, engine for
  // Supertonic) so a long mixed-engine list stays browsable.
  const groups = voices.reduce<Record<string, Voice[]>>((acc, voice) => {
    const key = voice.group || voice.locale || 'Other';
    (acc[key] ||= []).push(voice);
    return acc;
  }, {});

  useEffect(() => {
    fetchSampleText()
      .then(setSampleText)
      .catch(() => undefined);
  }, []);

  const stop = () => {
    const el = audioRef.current;
    if (el) {
      el.pause();
      el.currentTime = 0;
    }
    setIsPlaying(false);
    setIsLoading(false);
  };

  // Switching voice or speed invalidates whatever is playing.
  useEffect(() => stop(), [value, speed]);

  // Don't leave a sample playing when the component goes away.
  useEffect(() => () => audioRef.current?.pause(), []);

  const play = () => {
    if (!value) return;
    setPreviewError(null);
    setIsLoading(true);

    // A fresh element each time avoids stale state from a previous voice.
    const el = new Audio(previewUrl(value, speed));
    audioRef.current = el;

    // The first sample for a voice has to be synthesised, so "loading" lasts
    // until playback actually begins rather than until the request is sent.
    el.onplaying = () => {
      setIsLoading(false);
      setIsPlaying(true);
    };
    el.onended = () => {
      setIsPlaying(false);
      setIsLoading(false);
    };
    el.onerror = () => {
      setIsLoading(false);
      setIsPlaying(false);
      setPreviewError('Could not play a preview for this voice.');
    };

    void el.play().catch(() => {
      setIsLoading(false);
      setPreviewError('Could not play a preview for this voice.');
    });
  };

  const busy = isLoading || isPlaying;

  return (
    <div>
      <div className="mb-2 flex items-center justify-between gap-2">
        <label
          htmlFor="voice-select"
          className="flex items-center gap-2 text-sm font-medium text-muted"
        >
          <Mic size={14} />
          Voice
        </label>
        {/* The dropdown is for picking a known voice; this is for finding one. */}
        <button
          type="button"
          onClick={onBrowse}
          disabled={!hasVoices}
          className="flex items-center gap-1 text-xs text-muted hover:text-accent disabled:cursor-not-allowed disabled:opacity-40"
        >
          <LayoutGrid size={12} />
          See all {voices.length} voices
        </button>
      </div>

      <div className="flex gap-2">
        <div className="relative flex-1">
          <select
            id="voice-select"
            value={value}
            disabled={disabled || !hasVoices}
            onChange={(e) => onChange(e.target.value)}
            className="w-full appearance-none rounded-btn border border-line bg-card px-4 py-3 pr-10 text-ink outline-none hover:border-accent/60 focus:border-accent disabled:cursor-not-allowed disabled:opacity-50"
          >
            {hasVoices ? (
              Object.entries(groups).map(([accent, group]) => (
                <optgroup key={accent} label={accent}>
                  {group.map((voice) => (
                    <option key={voice.id} value={voice.id}>
                      {voice.label}
                    </option>
                  ))}
                </optgroup>
              ))
            ) : (
              <option value="">No voices installed</option>
            )}
          </select>
          <ChevronDown
            size={16}
            className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-muted"
          />
        </div>

        <button
          type="button"
          onClick={busy ? stop : play}
          disabled={!hasVoices || !value}
          title={busy ? 'Stop the preview' : 'Hear how this voice sounds'}
          aria-label={busy ? 'Stop preview' : 'Preview this voice'}
          className="flex shrink-0 items-center gap-2 rounded-btn border border-line bg-card px-4 text-sm font-medium text-ink hover:border-accent hover:text-accent disabled:cursor-not-allowed disabled:opacity-40"
        >
          {isLoading ? (
            <Loader2 size={15} className="animate-spin text-accent" />
          ) : isPlaying ? (
            <Square size={14} className="text-accent" />
          ) : (
            <Play size={14} />
          )}
          <span className="hidden sm:inline">
            {isLoading ? 'Loading' : isPlaying ? 'Stop' : 'Preview'}
          </span>
        </button>
      </div>

      {/* Show the words being spoken so the sample can be followed along. */}
      {hasVoices && sampleText && (
        <p className="mt-2.5 font-reader text-[13px] leading-snug text-muted italic">
          “{sampleText}”
        </p>
      )}

      {isLoading && (
        <p className="mt-2 text-xs text-muted animate-pulse-soft">
          Synthesising the first sample for {selected?.name ?? 'this voice'} — later previews
          are instant.
        </p>
      )}

      {previewError && <p className="mt-2 text-sm text-danger">{previewError}</p>}

      {!hasVoices && (
        <p className="mt-2 text-sm text-warning">
          No voice models found. Download at least one into{' '}
          <code className="rounded bg-surface px-1 py-0.5 text-xs">backend/piper/voices/</code> —
          see the README.
        </p>
      )}
    </div>
  );
}
